### PR TITLE
Math magicians: components

### PR DESCRIPTION
**Pull request by zhorabay**
- [ ] In this branch, I:
- Created a new directory called **components**.
- Inside components, created a new **Calculator.js** file.
- In Calculator.js, created a React component that matches the design.
- Implemented the design only (JSX and CSS).
- Used functional components.
- Created a child component.
- Tested it in the browser.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @zhorabay, can you remove the live demo section for now and add it when your project is deployed?

**Comment by zhorabay** [comment]
@prolajumokeoni Hi, thank you for your review. I fixed it.

**Comment by prolajumokeoni** [comment]
> @prolajumokeoni Hi, thank you for your review. I fixed it.

Great you will receive a review soon 👍🏿

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @zhorabay 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Calculator component is a functional component
✔️  Design matches wireframe 



## Required Changes ♻️

- [ ] Kindly delete the boiler plate template files that was added by the Create React App command  in your project, see screenshot below ⬇️ 
Screenshot_183

- [ ] Kindly add back the App.js component, the Calculator component should be imported into the App.js component, please remember that the App.js should also be a functional component 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShadyShawkat — APPROVED** [review]
## Hi @zhorabay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
